apiVersion: apps/v1
kind: ReplicaSet
metadata:  
  name: nginx
spec:  
  replicas: 2  
  selector:    
    matchLabels:      
      project: my-web     
  template:   
    metadata:      
        name: nginx      
        labels:        
          project: my-web        
          service: web        
          version: "0.1"    
    spec:      
        containers:      
        - name: nginx        
          image: nginx        
          ports:        
          - containerPort: 80
